### PR TITLE
add dockerfile

### LINKED ISSUE #7: Docker image
Hi there,

I have used this script several times and it is working just fine. 
Though, I think it would be nice to have a Dockerfile and ability to run this script in container.

### PR DESCRIPTION
**Pull request by kiddo3**
Resolves #7

### CODE REVIEW

**Review by techgaun — APPROVED** [review]

**Comment by techgaun** [comment]
:ok_hand: :purple_heart: :fire: :100: :rocket: **LGTM** :rocket: :100: :fire: :purple_heart: :ok_hand:

**Comment by kiddo3** [comment]
Can you please add the "hacktoberfest-accepted" label to the PR, please ? :)

**Comment by techgaun** [comment]
here you go

**Comment by kiddo3** [comment]
Thanks!

**Pull request merged**
